
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_NAME_SUCCESS = 'UPDATE_CATEGORY_NAME_SUCCESS';
